### ISSUE TITLE
emergency

### ISSUE THREAD

**Issue by zyx918** [thuml/predrnn-pytorch#10]
When I type 'sh predrnn_mnist_train.sh' at the terminal and run the code, I get an error ' No such file or directory: '/workspace/wuhaixu/predrnn/data/moving-mnist-example/moving-mnist-valid.npz''. Why does 'args' of 'run.py' not work? If I just use 'mnist_model.ckpt', and type 'python run.py', then I get an error'RuntimeError: Error(s) in loading state_dict for RNN:
        Missing key(s) in state_dict: "cell_list.0.conv_x.1.weight", "cell_list.0.conv_x.1.bias", "cell_list.0.conv_h.1.weight", "cell_list.0.conv_h.1.bias", "cell_list.0.conv_m.1.weight", "cell_list.0.conv_m.1.bias", "cell_list.0.conv_o.1.weight", "cell_list.0.conv_o.1.bias", "cell_list.1.conv_x.1.weight", "cell_list.1.conv_x.1.bias", "cell_list.1.conv_h.1.weight", "cell_list.1.conv_h.1.bias", "cell_list.1.conv_m.1.weight", "cell_list.1.conv_m.1.bias", "cell_list.1.conv_o.1.weight", "cell_list.1.conv_o.1.bias", "cell_list.2.conv_x.1.weight", "cell_list.2.conv_x.1.bias", "cell_list.2.conv_h.1.weight", "cell_list.2.conv_h.1.bias", "cell_list.2.conv_m.1.weight", "cell_list.2.conv_m.1.bias", "cell_list.2.conv_o.1.weight", "cell_list.2.conv_o.1.bias", "cell_list.3.conv_x.1.weight", "cell_list.3.conv_x.1.bias", "cell_list.3.conv_h.1.weight", "cell_list.3.conv_h.1.bias", "cell_list.3.conv_m.1.weight", "cell_list.3.conv_m.1.bias", "cell_list.3.conv_o.1.weight", "cell_list.3.conv_o.1.bias".
        Unexpected key(s) in state_dict: "adapter.weight".
        size mismatch for cell_list.0.conv_x.0.weight: copying a param with shape torch.Size([896, 16, 5, 5]) from checkpoint, the shape in current model is torch.Size([448, 16, 5, 5]).
        size mismatch for cell_list.0.conv_h.0.weight: copying a param with shape torch.Size([512, 128, 5, 5]) from checkpoint, the shape in current model is torch.Size([256, 64, 5, 5]).
        size mismatch for cell_list.0.conv_m.0.weight: copying a param with shape torch.Size([384, 128, 5, 5]) from checkpoint, the shape in current model is torch.Size([192, 64, 5, 5])....'. What should I do? @wangyb15

**Comment by tinyrobots** [comment]
What was the resolution to this? I have exactly the same error regarding `Missing key(s) in state_dict`.
