### ISSUE TITLE
Question about reshape_patch function

### ISSUE THREAD

**Issue by Prevalenter** [thuml/predrnn-pytorch#12]
what the role of  reshape_patch in core/utils/preprocess?
I found that adding the patch_size parameter can significantly speed up the training process and reduce the cuda memory.

And I test function reshape_patch using the code following:

```
    img = cv2.imread('cat.jpeg', 0)
    img = img[np.newaxis, np.newaxis, :, :, np.newaxis]
    img_patched = reshape_patch(img, 3)
```

and I show the img(a gray image) and img_patched:
![1624435126(1)](https://user-images.githubusercontent.com/31162098/123059543-79b58e80-d43c-11eb-946d-1fa1f70ac2d6.png)

So is this function used to reduce the spatial resolution of the image? 

And thanks for your good work!

**Comment by wuhaixu2016** [comment]
Yes, this operation is to reduce the spatial resolution, but it still keeps the complete information by adding the number of channels.

**Comment by Prevalenter** [comment]
Thansk for your answer！
And  I did not find the description of this operation in the paper. Does this operation refer to other codes? or proposed by your team?

**Comment by wuhaixu2016** [comment]
I think this is a widely-used idea in computer vision, such as super-resolution. We implemented this operation ourselves in this paper.

**Comment by Prevalenter** [comment]
ok, thanks for your answer.

**Comment by ZHAIXINGZHAIYUE** [comment]
> I think this is a widely-used idea in computer vision, such as super-resolution. We implemented this operation ourselves in this paper.

这样做有什么好处吗？ 我有点想不明白，请求解惑
