### ISSUE TITLE
Can the length of testing input sequence be different from that of the training input

### ISSUE THREAD

**Issue by chisam0217** [thuml/predrnn-pytorch#14]
Hi,
Thank you for sharing with the great work.
I wonder if the length of input sequence for training and testing can be different? To be specific, for training, a length-10 video clip is fed into the network, while for testing, only one frame is used as input.

**Comment by wuhaixu2016** [comment]
Yes, you can set the length of input or output as any value. This benefits from the recurrent structure with temporal parameter sharing.

**Comment by chisam0217** [comment]
Got it, thank you!
