### ISSUE TITLE
predicted results

### ISSUE THREAD

**Issue by buaa-luzhi** [thuml/predrnn-pytorch#16]
@wuhaixu2016
Hello, thank you for sharing your work. 
My test results on the KTH dataset are shown below.
![微信图片_20210730163626](https://user-images.githubusercontent.com/28650172/127626164-e34a4e65-4814-45c9-a937-1ef8886763a6.png)
My understanding is to input 20 frames of images and predict 19 frames.
However, why are these two sequences almost identical instead of predicting future actions.

Looking forward to your reply, thank you so much!!!

**Comment by buaa-luzhi** [comment]
For example, the first 10 frames are given and the last 10 frames are predicted.

**Comment by wuhaixu2016** [comment]
Hi, Thanks for your attention. This is all about the **filename of prediction results.** 

In your cases, the total length is 20 and the input length is 10. The model output is 20-1=19 images under the next-frame-prediction setting. The 'pd' index is from 2 to 20.

I have fix this by update the results filename index. You can ref to the latest commit.

**Comment by buaa-luzhi** [comment]
Thank you very mcuh for your kind reply.
In your reply,  what does under the next frame prediction setting mean? 
Don't you input several frames of the model continuously and predict several frames in the future?
For example, 
input: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
predict: 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
Thanks again!

**Comment by wuhaixu2016** [comment]
'Next frame prediction' is 'input i predict (i+1)' during the training.
This is a standard setting of predictive learning. You can read the paper or code for more details.
