### ISSUE TITLE
How to add attention mechanism by torch.nn.MultiheadAttention

### ISSUE THREAD

**Issue by wuxiaofei01** [thuml/predrnn-pytorch#17]
Thank you so much for sharing your work , Due to the needs of the question, how to add attention mechanism by torch.nn.MultiheadAttention for convenience

**Comment by wuhaixu2016** [comment]
Thanks for your attention. It is a good idea to add the attention mechanism to deep models. But this idea is parallel with our model. Maybe you can ref to Transformer-based models for more insights. Hope this is helpful to you.
