### ISSUE TITLE
Calculate model size

### ISSUE THREAD

**Issue by Mareeta26** [thuml/predrnn-pytorch#19]
Hi,
May I kindly know how to calculate the model sizes/ memory/flops reported in Table  2 and 3 ?
Can you please share the code snippet ?

Thanks!

**Comment by wuhaixu2016** [comment]
For the model size and flops, you can calculate them precisely based on the sum of all basic operations.
For the memory, you can record the memory occupation of GPUs (use nvidia-smi to check).
Also, some packages can make this process easier, such as thop.

**Comment by Mareeta26** [comment]
Thank you!
