### ISSUE TITLE
How to get the Traffic4cast dataset?

### ISSUE THREAD

**Issue by Mareeta26** [thuml/predrnn-pytorch#21]
Hi,
Could you please share the Traffic4cast dataset used? I couldn't get the 2019 data from the website.
Thanks in advance!

**Comment by wuhaixu2016** [comment]
I confirm that the dataset is public. You can find it here (as described in the main text): https://www.iarai.ac.at/traffic4cast/2019-competition/

**Comment by Mareeta26** [comment]
@wuhaixu2016 , Though the site is there, the link to download data is not working. Please see the attached screensho
![Screen Shot 2021-09-21 at 9 54 47 PM](https://user-images.githubusercontent.com/83035804/134285689-d34d4d94-28e6-400b-9e0c-f473d4308acb.png)
