### ISSUE TITLE
Moving MNIST 3 digits

### ISSUE THREAD

**Issue by Mareeta26** [thuml/predrnn-pytorch#24]
Hi,
Thanks for the repo. I could get good results with your pretrained model.
May I know how we can use the pretrained model for 3 digits Moving MNIST?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your good question.
(1) You can get the dataset with 3 digits from predefined generation rules.
(2) It is a good question: is the model pretrained from 2-digits-dataset also useful for 3-digits-dataset? I think this is an important and interesting question. You can follow these two papers from Yao and Wang for more details:

- ModeRNN: Harnessing Spatiotemporal Mode Collapse in Unsupervised Predictive Learning (https://arxiv.org/abs/2110.03882)
- Unsupervised Transfer Learning for Spatiotemporal Predictive Networks (https://arxiv.org/abs/2009.11763)

**Comment by Mareeta26** [comment]
Hi @wuhaixu2016,
May I know how I can get the dataset with 3 digits? Where can I find the predefined generation rules? Can you please share the code?

Thansk!
