### ISSUE TITLE
Whether the Moving_MNIST dataset volume in PredRNN++ is the same as the code repo?

### ISSUE THREAD

**Issue by ILoveStudying** [thuml/predrnn-pytorch#27]
'Hi, this code repo is correct. We will rephrase the paper soon.

_Originally posted by @wuhaixu2016 in https://github.com/thuml/predrnn-pytorch/issues/26#issuecomment-968199072_'

Thanks for your reply. I couldn't reproduce the performance on Moving_MNIST in PredRNN++ anyway.  So I would like to know whether the Moving_MNIST dataset volume in PredRNN++ is the same as the code repo? If not, which volume setting is the experiment in PredRNN++ based on?
Looking forward to your reply. Thanks very much!

**Comment by wuhaixu2016** [comment]
Hi, you can get the dataset and code here ⬇️
https://github.com/Yunbo426/predrnn-pp

**Comment by ILoveStudying** [comment]
Yes, I find that the Moving_MNIST dataset provided in code repo [PredRNN++ ](https://github.com/Yunbo426/predrnn-pp) is still inconsistent with the paper (PredRNN++). So which volume setting is the experiment in PredRNN++ based on?
Thanks!

**Comment by wuhaixu2016** [comment]
I think you can totally follow the dataset since PredRNN, PredRNN++, PredRNN-V2 use the same Moving_mnist data.
