### ISSUE TITLE
What's the validation dataset for KTH_action, TaxiBJ, and Human3.6M?

### ISSUE THREAD

**Issue by ILoveStudying** [thuml/predrnn-pytorch#28]
Hi, I see that there are only training and test datasets for above  KTH_action, TaxiBJ, and Human3.6M.  So, what's about the validation dataset or there is no validation sequences in these datasets?
Thanks!

**Comment by wuhaixu2016** [comment]
Yes, there are no validation sequences in these datasets. 
Because the hyper-parameter is easy to tune, we always share the selection among datasets or determine by the convergence property of the training process.

**Comment by ILoveStudying** [comment]
Thanks

**Comment by wintercoming233** [comment]
How to add TaxiBJdataset ?
