### ISSUE TITLE
Guidance for custom dataset

### ISSUE THREAD

**Issue by Ranhuiryan** [thuml/predrnn-pytorch#34]
Hi, I'm wondering whether I can use my own data. Is there any guidelines for building custom dataset to train and test the model?

Thanks in advance.

**Comment by wuhaixu2016** [comment]
Hi, you can follow the examples in data_provider and add the new dataset name to https://github.com/thuml/predrnn-pytorch/blob/master/core/data_provider/datasets_factory.py
