### ISSUE TITLE
Generate a new Moving-MNIST dataset

### ISSUE THREAD

**Issue by Mareeta26** [thuml/predrnn-pytorch#36]
Hi,
May I know where can I find the code to generate a new Moving-MNIST dataset? I need to create subsets of different sizes.
Thank you,
Mareeta

**Comment by wuhaixu2016** [comment]
Hi, you may find this useful.
https://gitlab.fbk.eu/deep-learning/meteo-tn/-/blob/0beb24ead64ee37315b54eba1c7d70e384145ca6/nowcasting/movingmnist_iterator.py
