### ISSUE TITLE
Generate new Mnist dataset

### ISSUE THREAD

**Issue by Mareeta26** [thuml/predrnn-pytorch#37]
Hi, As mentioned in previous issue [here](https://github.com/thuml/predrnn-pytorch/issues/36#issuecomment-1200411837), may I know how did you include items like "clips", "dims" in the MNIST dataset?

Thank you!

**Comment by Anant808** [comment]
Hi @Mareeta26 and @wuhaixu2016,

Can you please help me. I have the same question. How do we include clips and dims in the moving mnist dataset.

Thank you for the help in advance.

**Comment by Anant808** [comment]
I now understand the need for the clips array.
This is my understanding. Writing this here for someone's reference. Please correct me if I am wrong:

It's used to create samples from the training and test dataset.
1.) The size of the training clip array = (2, 10000, 2) and testing clip array = (2, 2000, 2).
2.) The first dimension in each array is for input and second dimension is for output.
     So for training input = (dimension[0], 1000, 2) and for testing input = (dimension[0], 2000, 2).
     Training output = (dimension[1], 10000, 2), testing output = (dimension[1], 2000, 2).
3.) The 10000 and 2000 indicates the number of input/output sequences for each training and testing datasets.
4.) The last dimension has two values in each cell. The first value indicates the beginning of the sequence, the second value 
     indicates the number of images/frames to be taken in the sequence.
     For the last dimension: The next cell's first value = previous cell's first value + previous cell's second value.

**Comment by wuhaixu2016** [comment]
Hi, they are correct. Thanks for sharing your understanding.
