### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by GTziolas** [thuml/predrnn-pytorch#39]
When I try to execute the Moving MNIST script using a pretrained model (with arguments "--save_dir" and "--pretrained_model"), the error in the title appears. I believe the lines of code posted below cause the error in the title. 

https://github.com/thuml/predrnn-pytorch/blob/36ba2b63fa96da3a60c32127e48f517e04062201/run.py#L210-L212

**Comment by GTziolas** [comment]
The code above is not causing the error it seems, since I have commented it out and I still get it. My guess is though that somewhere the folders are being deleted and created and that's what causing the problem.

**Comment by wuhaixu2016** [comment]
Hi, sorry for this bug. We have not came across this problem. But if you want to run this code, you can redefine the model save way.
