### ISSUE TITLE
Calculation of MSE per frame

### ISSUE THREAD

**Issue by rafaela00castro** [thuml/predrnn-pytorch#4]
First of all, congrats on your code. I don't understand why don't you use the `gx` value of line 56 instead of the value used on line 59. Why are lines 57 and 58 necessary? ([link](https://github.com/thuml/predrnn-pytorch/blob/master/core/trainer.py#L56-L59)).  

````
            line 56: gx = img_out[:, i, :, :, :]
            line 57: gx = np.maximum(gx, 0)
            line 58: gx = np.minimum(gx, 1)
            line 59: mse = np.square(x - gx).sum()
```` 
Thanks in advance!

**Comment by zhangfuhan** [comment]
maybe it like np.clip(output,0.0,1.0) . because the value of output is range(0,1) after normalization in the network.
