### ISSUE TITLE
Kth dataset： inf error

### ISSUE THREAD

**Issue by DUAT-Maker** [thuml/predrnn-pytorch#42]
![image](https://user-images.githubusercontent.com/95007001/206964688-71d07adf-945a-413a-b554-0b10a17b0fd2.png)

**Comment by dxs07** [comment]
I have also encountered corresponding problems, which should be due to issues with data normalization. You can try to change the 'dtype=np. int8' in line 165 to 'dtype=np. float32' in the file kth_action, which may solve your problem.

**Comment by wuhaixu2016** [comment]
Hi, this problem is solved in the latest commit.
