### ISSUE TITLE
Why is MSE calculated with "sum" instead of "mean"?

### ISSUE THREAD

**Issue by ANNMS-Projects** [thuml/predrnn-pytorch#47]
Why is MSE calculated with "sum" instead of "mean"?
![image](https://github.com/thuml/predrnn-pytorch/assets/128010737/2cbfa460-4de4-4d1a-b929-18b892bf05cc)

Is the amount of parameters of CrevNet really so small? It seems to be just the amount of parameters contained in a convolution of size 256x256x3x3 stored in float32.
![image](https://github.com/thuml/predrnn-pytorch/assets/128010737/b4fa8cd4-0770-4bcd-8ec1-08feb260edeb)

**Comment by wuhaixu2016** [comment]
Hi, we adopt the 'sum' following convention of previous paper. mean is also reasonable.

But, we don't know about you mentioned paper CrevNet. You can reach to their authors for this question.
