### ISSUE TITLE
Question about the purpose of dividing the data set into two categories: category_1 and category_2

### ISSUE THREAD

**Issue by jlzcode** [thuml/predrnn-pytorch#7]
In kth_action.py, in line 108, why the dataset is split into two categories, categoty_1 and category_2?

        self.category_1 = ['boxing', 'handclapping', 'handwaving', 'walking']
        self.category_2 = ['jogging', 'running']

Thanks!

**Comment by wuhaixu2016** [comment]
Hi, we split the dataset as training data and test data. The training data is from category_1 and test data is from category_2.
