### ISSUE TITLE
Question about the "real_input_flag" in the run.py and the "mask_true" in the predrnn.py

### ISSUE THREAD

**Issue by Rayage277** [thuml/predrnn-pytorch#8]
Hey, buddy! Could you please explain the tensor: real_input_flag and mask_true, what does it do.

**Comment by wuhaixu2016** [comment]
This is for scheduled sampling in PredRNN and reverse scheduled sampling in PredRNN-v2.
We mask some input frames randomly to bridge the gap between encoder and decoder.
So, these two tensors are the random masks for input frames with 0-1 values.

**Comment by Rayage277** [comment]
Thanks!
